# Generated by Django 6.0.6 on 2026-06-11 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0006_systemauditlog_dhsuploadeddataset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("UPLOAD", "Dataset Upload"),
                    ("COMPUTE", "Indicator Computation"),
                    ("USER_CREATE", "User Created"),
                    ("USER_UPDATE", "User Updated"),
                    ("USER_DELETE", "User Deleted"),
                    ("LOGIN", "Admin Login"),
                    ("LOGOUT", "Admin Logout"),
                    ("DATA_DELETE", "Data Deleted"),
                    ("INVITE_SENT", "Invitation Sent"),
                    ("INVITE_ACCEPT", "Invitation Accepted"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("analyst", "Analyst"), ("admin", "Admin")],
                        default="analyst",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
