# Generated by Django 6.0.1 on 2026-06-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_systemauditlog_dhsuploadeddataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='level',
            field=models.CharField(choices=[('district', 'District'), ('province', 'Province'), ('national', 'National')], default='district', max_length=10),
        ),
    ]
